import $ from 'jquery';
import commonInput from './common/input';
import burger from '../blocks/burger/burger';
import upBtn from '../blocks/up-btn/up-btn';
import select from '../blocks/select/select';
import searchBar from '../blocks/search-bar/search-bar';
import mainSlider from '../blocks/main-slider/main-slider';
import filter from '../blocks/filter/filter';
import textField from '../blocks/text-field/text-field';
import submenu from '../blocks/submenu/submenu';
import timeline from '../blocks/timeline/timeline';
import models from '../blocks/models/models';
import selectCurrency from '../blocks/select-currency/select-currency';
import counter from '../blocks/counter/counter';
import modal from '../blocks/modal/modal';
import yachtSlider from '../blocks/yacht-slider/yacht-slider';

$(() => {
  commonInput();
  burger();
  select();
  searchBar();
  mainSlider();
  submenu();
  filter();
  textField();
  upBtn();
  timeline();
  models();
  selectCurrency();
  counter();
  modal();
  yachtSlider();
});
